Added package.json

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,9 @@
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "main" ]; then
-  echo "You can't push directly to main - please check out a branch."
-  exit 1
-fi
+# if [ "$branch" = "main" ]; then
+#   echo "You can't push directly to main - please check out a branch."
+#   exit 1
+# fi
 
 npm run compile
 
